apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 65.1.1
    helm:
      values: |
        grafana:
          adminPassword: admin
        prometheusOperator:
          admissionWebhooks:
            enabled: false
            patch:
              enabled: false
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector: {}
            ruleSelectorNilUsesHelmValues: false
            ruleNamespaceSelector: {}
        alertmanager:
          alertmanagerSpec:
            secrets:
              - alertmanager-gmail
          config:
            global:
              smtp_smarthost: smtp.gmail.com:587
              smtp_from: trucltde170267@fpt.edu.vn
              smtp_auth_username: trucltde170267@fpt.edu.vn
              smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-gmail/password
              smtp_require_tls: true
            route:
              receiver: "null"
              group_by:
                - alertname
                - namespace
              group_wait: 10s
              group_interval: 1m
              repeat_interval: 30m
              routes:
                - receiver: email-personal
                  matchers:
                    - alertname = "ApiHighErrorRate"
                - receiver: email-personal
                  matchers:
                    - alertname = "TestMailAlert"
            receivers:
              - name: "null"
              - name: email-personal
                email_configs:
                  - to: trucltde170267@fpt.edu.vn
                    send_resolved: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
